// <auto-generated />
namespace RoastMeApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class NullIslike : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullIslike));
        
        string IMigrationMetadata.Id
        {
            get { return "201706211840130_NullIslike"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
